CREATE TABLE `GOODS` {
    `ID` BIGINT UNSIGNED NOT NULL COMMENT '主键',
    `TITLE` VARCHAR(128) NOT NULL COMMENT '商品标题',
    `PRICE` BIGINT NOT NULL COMMENT '商品一口价',
    `BRAND_NAME` VARCHAR(32) NOT NULL COMMENT '品牌名称',
    `PIC_PATH` VARCHAR(128) NOT NULL COMMENT '主图地址',
    `USE_FLAG` TINYINT NOT NULL COMMENT '启用标记 0-停用 1-启用',
    `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
    `LAST_MODIFY_TIME` DATETIME NOT NULL COMMENT '最后修改时间',
    PRIMARY KEY (`ID`) USING BTREE
} ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic COMMENT = '商品信息表';

CREATE TABLE `GOODS_SKU` {
    `ID` BIGINT UNSIGNED NOT NULL COMMENT '主键',
    `GOOD_ID` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
    `PROP_NAME` VARCHAR(32) NOT NULL COMMENT '属性名',
    `PRICE` BIGINT NOT NULL COMMENT '一口价',
    `PIC_PATH` VARCHAR(128) NOT NULL COMMENT '主图地址',
    `USE_FLAG` TINYINT NOT NULL COMMENT '启用标记 0-停用 1-启用',
    `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
    `LAST_MODIFY_TIME` DATETIME NOT NULL COMMENT '最后修改时间',
    PRIMARY KEY (`ID`) USING BTREE
} ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic COMMENT = '商品SKU信息表';

-- 简单记录SKU库存信息, 不做库存管理, 热点数据分离用
CREATE TABLE `GOODS_STOCK` {
    `ID` BIGINT UNSIGNED NOT NULL COMMENT '主键',
    `GOOD_ID` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
    `SKU_ID` BIGINT UNSIGNED NOT NULL COMMENT 'SKUID',
    `STOCK_NUM` BIGINT NOT NULL COMMENT '库存数量',
    `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
    `LAST_MODIFY_TIME` DATETIME NOT NULL COMMENT '最后修改时间',
    PRIMARY KEY (`ID`) USING BTREE
} ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic COMMENT = '商品库存表';