-- 默认自营业务，固定商家不记录, 默认供应商不记录, 默认仓库不记录, 外部物流单号
-- 字段冗余同时集成版本备份功能, 不另外开表
CREATE TABLE `ORDER` {
    `ID` BIGINT UNSIGNED NOT NULL COMMENT '主键',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `USER_NICK_NAME` VARCHAR(64) NOT NULL COMMENT '买家昵称',
    `GOOD_ID` BIGINT UNSIGNED NOT NULL COMMENT '商品编码',
    `SKU_ID` BIGINT UNSIGNED NOT NULL COMMENT 'SKUID',
    `GOOD_NAME` VARCHAR(128) NOT NULL COMMENT '商品名称',
    `STATUS` TINYINT NOT NULL COMMENT '订单状态',
    `ORDER_TIME` DATETIME NOT NULL COMMENT '下单时间',
    `PAY_TIME` DATETIME NOT NULL COMMENT '支付时间',
    `CLOSE_TIME` DATETIME NOT NULL COMMENT '销单时间',
    `SALE_AMT` BIGINT NOT NULL COMMENT '售价金额(分精度)',
    `PAY_AMT` BIGINT NOT NULL COMMENT '买家支付金额(分精度)',
    `PLANT_TOTAL_FEE` BIGINT NOT NULL COMMENT '平台总计扣减费用(分精度)',
    `CONSIGNEE_NAME` VARCHAR(32) NOT NULL COMMENT '收货人姓名',
    `CONSIGNEE_PHONE` VARCHAR(16) NOT NULL COMMENT '收货人联系电话含固话',
    `CONSIGNEE_PROVINCE_NAME` VARCHAR(16) NOT NULL COMMENT '省份名称',
    `CONSIGNEE_CITY_NAME` VARCHAR(64) NOT NULL COMMENT '城市名称',
    `CONSIGNEE_COUNTY_NAME` VARCHAR(64) NOT NULL COMMENT '区县名称',
    `CONSIGNEE_STREET_ADDRESS` VARCHAR(256) NOT NULL COMMENT '具体街道地址',
    `MEMO` VARCHAR(256) NOT NULL COMMENT '买家备注',
    `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
    `LAST_MODIFY_TIME` DATETIME NOT NULL COMMENT '最后修改时间',
    PRIMARY KEY (`ID`) USING BTREE,
    INDEX IDX_USER_ID (`USER_ID`)
} ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic COMMENT = '订单信息表';