CREATE TABLE `USER` {
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `ACCOUNT` VARCHAR(16) NOT NULL COMMENT '账号',
    `NICK_NAME` VARCHAR(64) NOT NULL COMMENT '用户昵称',
    `LAST_LOGIN_TIME` DATETIME NOT NULL COMMENT '上次登录时间',
    `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
    `LAST_MODIFY_TIME` DATETIME NOT NULL COMMENT '最后修改时间',
    PRIMARY KEY (`ID`) USING BTREE
} ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic COMMENT = '用户信息表';

CREATE TABLE `USER_SECRET` {
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '用户id',
    `PWD` VARCHAR(64) NOT NULL COMMENT '密码密文',
    `USE_FLAG` TINYINT NOT NULL COMMENT '启用标记 0-无效 1-有效',
    `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
    `LAST_MODIFY_TIME` DATETIME NOT NULL COMMENT '最后修改时间',
    PRIMARY KEY (`ID`) USING BTREE
} ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic COMMENT = '用户密码表';

CREATE TABLE `USER_CONSIGNEE_INFO` {
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `NAME` VARCHAR(32) NOT NULL COMMENT '收货人姓名',
    `PHONE` VARCHAR(16) NOT NULL COMMENT '收货人联系电话含固话',
    `PROVINCE_NAME` VARCHAR(16) NOT NULL COMMENT '省份名称',
    `CITY_NAME` VARCHAR(64) NOT NULL COMMENT '城市名称',
    `COUNTY_NAME` VARCHAR(64) NOT NULL COMMENT '区县名称',
    `STREET_ADDRESS` VARCHAR(256) NOT NULL COMMENT '具体街道地址',
    `SHOW_SORT` TINYINT NOT NULL COMMENT '展示排序',
    `LAST_LOGIN_TIME` DATETIME NOT NULL COMMENT '上次登录时间',
    `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
    `LAST_MODIFY_TIME` DATETIME NOT NULL COMMENT '最后修改时间',
    PRIMARY KEY (`ID`) USING BTREE
} ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic COMMENT = '用户收货信息表';
